### ISSUE TITLE
Asking username and password when we run the code

### ISSUE THREAD

**Issue by SanketMishrikotkar** [saitejach1998/Nest---Event-Management#1]
What is the username & password?

**Comment by saitejach1998** [comment]
this is just the front-end of the app. You would need to run a backend by yourself for content delivery and authentication.

**Comment by SanketMishrikotkar** [comment]
Then what to enter the username and password??

**Comment by saitejach1998** [comment]
The app should be connected to a database that you have to build YOURSELF. Your backend server should have an login endpoint which should check for the correct credentials in your database.

You can follow this guide to create a simple backend server using Node and MongoDB

https://codeburst.io/writing-a-crud-app-with-node-js-and-mongodb-e0827cbbdafb
